openapi: 3.0.0
info:
  version: "1.0.0"
  x-release: v4
  title: Amazon Managed Blockchain Accessors Invitations API
  description: <p/> <p>Amazon Managed Blockchain is a fully managed service for creating and managing blockchain networks using open-source frameworks. Blockchain allows you to build applications where multiple parties can securely and transparently run transactions and share data without the need for a trusted, central authority.</p> <p>Managed Blockchain supports the Hyperledger Fabric and Ethereum open-source frameworks. Because of fundamental differences between the frameworks, some API actions or data types may only apply in the context of one framework and not the other. For example, actions related to Hyperledger Fabric network members such as <code>CreateMember</code> and <code>DeleteMember</code> don't apply to Ethereum.</p> <p>The description for each action indicates the framework or frameworks to which it applies. Data types and properties that apply only in the context of a particular framework are similarly indicated.</p>
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: managedblockchain
  x-aws-signingName: managedblockchain
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/managedblockchain-2018-09-24.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://managedblockchain.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The ManagedBlockchain multi-region endpoint
- url: https://managedblockchain.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The ManagedBlockchain multi-region endpoint
- url: http://managedblockchain.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The ManagedBlockchain endpoint for China (Beijing) and China (Ningxia)
- url: https://managedblockchain.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The ManagedBlockchain endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Invitations
paths:
  /invitations:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    get:
      operationId: ListInvitations
      description: <p>Returns a list of all invitations for the current Amazon Web Services account.</p> <p>Applies only to Hyperledger Fabric.</p>
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListInvitationsOutput'
        '480':
          description: InvalidRequestException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidRequestException'
        '481':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
        '482':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
        '483':
          description: ThrottlingException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottlingException'
        '484':
          description: ResourceLimitExceededException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceLimitExceededException'
        '485':
          description: InternalServiceErrorException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServiceErrorException'
      parameters:
      - name: maxResults
        in: query
        required: false
        description: The maximum number of invitations to return.
        schema:
          type: integer
          minimum: 1
          maximum: 100
      - name: nextToken
        in: query
        required: false
        description: The pagination token that indicates the next set of results to retrieve.
        schema:
          type: string
          maxLength: 128
      - name: MaxResults
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: NextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      summary: Amazon Managed Blockchain List Invitations
      tags:
      - Invitations
  /invitations/{invitationId}:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    delete:
      operationId: RejectInvitation
      description: <p>Rejects an invitation to join a network. This action can be called by a principal in an Amazon Web Services account that has received an invitation to create a member and join a network.</p> <p>Applies only to Hyperledger Fabric.</p>
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RejectInvitationOutput'
        '480':
          description: InvalidRequestException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidRequestException'
        '481':
          description: IllegalActionException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IllegalActionException'
        '482':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
        '483':
          description: ResourceNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundException'
        '484':
          description: ThrottlingException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottlingException'
        '485':
          description: InternalServiceErrorException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServiceErrorException'
      parameters:
      - name: invitationId
        in: path
        required: true
        description: The unique identifier of the invitation to reject.
        schema:
          type: string
          minLength: 1
          maxLength: 32
      summary: Amazon Managed Blockchain Reject Invitation
      tags:
      - Invitations
components:
  parameters:
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
  schemas:
    InvitationList:
      type: array
      items:
        $ref: '#/components/schemas/Invitation'
    NameString:
      type: string
      pattern: .*\S.*
      minLength: 1
      maxLength: 64
    InvitationStatus:
      type: string
      enum:
      - PENDING
      - ACCEPTED
      - ACCEPTING
      - REJECTED
      - EXPIRED
    Invitation:
      type: object
      properties:
        InvitationId:
          allOf:
          - $ref: '#/components/schemas/ResourceIdString'
          - description: The unique identifier for the invitation.
        CreationDate:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: The date and time that the invitation was created.
        ExpirationDate:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: The date and time that the invitation expires. This is the <code>CreationDate</code> plus the <code>ProposalDurationInHours</code> that is specified in the <code>ProposalThresholdPolicy</code>. After this date and time, the invitee can no longer create a member and join the network using this <code>InvitationId</code>.
        Status:
          allOf:
          - $ref: '#/components/schemas/InvitationStatus'
          - description: <p>The status of the invitation:</p> <ul> <li> <p> <code>PENDING</code> - The invitee hasn't created a member to join the network, and the invitation hasn't yet expired.</p> </li> <li> <p> <code>ACCEPTING</code> - The invitee has begun creating a member, and creation hasn't yet completed.</p> </li> <li> <p> <code>ACCEPTED</code> - The invitee created a member and joined the network using the <code>InvitationID</code>.</p> </li> <li> <p> <code>REJECTED</code> - The invitee rejected the invitation.</p> </li> <li> <p> <code>EXPIRED</code> - The invitee neither created a member nor rejected the invitation before the <code>ExpirationDate</code>.</p> </li> </ul>
        NetworkSummary:
          $ref: '#/components/schemas/NetworkSummary'
        Arn:
          allOf:
          - $ref: '#/components/schemas/ArnString'
          - description: The Amazon Resource Name (ARN) of the invitation. For more information about ARNs and their format, see <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Names (ARNs)</a> in the <i>Amazon Web Services General Reference</i>.
      description: <p>An invitation to an Amazon Web Services account to create a member and join the network.</p> <p>Applies only to Hyperledger Fabric.</p>
    InternalServiceErrorException: {}
    RejectInvitationOutput:
      type: object
      properties: {}
    ResourceIdString:
      type: string
      minLength: 1
      maxLength: 32
    ArnString:
      type: string
      pattern: ^arn:.+:.+:.+:.+:.+
      minLength: 1
      maxLength: 1011
    AccessDeniedException: {}
    NetworkSummary:
      type: object
      properties:
        Id:
          allOf:
          - $ref: '#/components/schemas/ResourceIdString'
          - description: The unique identifier of the network.
        Name:
          allOf:
          - $ref: '#/components/schemas/NameString'
          - description: The name of the network.
        Description:
          allOf:
          - $ref: '#/components/schemas/DescriptionString'
          - description: An optional description of the network.
        Framework:
          allOf:
          - $ref: '#/components/schemas/Framework'
          - description: The blockchain framework that the network uses.
        FrameworkVersion:
          allOf:
          - $ref: '#/components/schemas/FrameworkVersionString'
          - description: The version of the blockchain framework that the network uses.
        Status:
          allOf:
          - $ref: '#/components/schemas/NetworkStatus'
          - description: The current status of the network.
        CreationDate:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: The date and time that the network was created.
        Arn:
          allOf:
          - $ref: '#/components/schemas/ArnString'
          - description: The Amazon Resource Name (ARN) of the network. For more information about ARNs and their format, see <a href="https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html">Amazon Resource Names (ARNs)</a> in the <i>Amazon Web Services General Reference</i>.
      description: A summary of network configuration properties.
    ResourceLimitExceededException: {}
    IllegalActionException: {}
    ListInvitationsOutput:
      type: object
      properties:
        Invitations:
          allOf:
          - $ref: '#/components/schemas/InvitationList'
          - description: The invitations for the network.
        NextToken:
          allOf:
          - $ref: '#/components/schemas/PaginationToken'
          - description: The pagination token that indicates the next set of results to retrieve.
    ResourceNotFoundException: {}
    Framework:
      type: string
      enum:
      - HYPERLEDGER_FABRIC
      - ETHEREUM
    FrameworkVersionString:
      type: string
      minLength: 1
      maxLength: 8
    DescriptionString:
      type: string
      maxLength: 128
    ThrottlingException: {}
    PaginationToken:
      type: string
      maxLength: 128
    InvalidRequestException: {}
    Timestamp:
      type: string
      format: date-time
    NetworkStatus:
      type: string
      enum:
      - CREATING
      - AVAILABLE
      - CREATE_FAILED
      - DELETING
      - DELETED
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/managedblockchain/
x-hasEquivalentPaths: true
